### ISSUE TITLE
UNITS FOR CREATED USER VARIABLE

### ISSUE THREAD

**Issue by tdcxs** [embention/ISS#22]
### Description of the problem

We create user variables like FT_IAS and desired IAS_User with the units (m/s)? but when w insert a chart with these variables in the worksapce, we cannot attribute units?

### Drag the downloaded zip, image and video

![image](https://user-images.githubusercontent.com/29060084/191272735-a7984076-733d-4dbc-84e4-5cdbc0cdf267.png)

**Comment by adm5** [comment]
related to https://github.com/embention/VeronteApp/issues/506

**Comment by tdcxs** [comment]
Hi @adm5, thank you for reply. I have no access to the link you just posted (404 page not found on GIthub)
